# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
dist_func <- function(pos, min = 0.01) {
    .Call('_Rforceatlas_dist_func', PACKAGE = 'Rforceatlas', pos, min)
}

#' @export
repl_func <- function(deg, dist, k = 400L) {
    .Call('_Rforceatlas_repl_func', PACKAGE = 'Rforceatlas', deg, dist, k)
}

#' @export
attr_func <- function(dist, wgts, deg, delta = 1.0, linlog = FALSE, nohubs = FALSE) {
    .Call('_Rforceatlas_attr_func', PACKAGE = 'Rforceatlas', dist, wgts, deg, delta, linlog, nohubs)
}

#' @export
grav_func <- function(pos, deg, orig, G = 1.0) {
    .Call('_Rforceatlas_grav_func', PACKAGE = 'Rforceatlas', pos, deg, orig, G)
}

#' @export
force_func <- function(attr, repl, grav, pos, dist) {
    .Call('_Rforceatlas_force_func', PACKAGE = 'Rforceatlas', attr, repl, grav, pos, dist)
}

#' @export
speed_func <- function(f_t0, f_t1, deg, tol = .1, s = .1, smax = 10.0) {
    .Call('_Rforceatlas_speed_func', PACKAGE = 'Rforceatlas', f_t0, f_t1, deg, tol, s, smax)
}

#' @export
forceatlas2 <- function(m, iter = 100L, linlog = FALSE, nohubs = FALSE, k = 400L, G = 1L, ks = 0.1, ksmax = 10.0, delta = 1.0, tol = 0.1, dim = 2L, init_pos = NULL, orig_pos = NULL, plotstep = 10L) {
    .Call('_Rforceatlas_forceatlas2', PACKAGE = 'Rforceatlas', m, iter, linlog, nohubs, k, G, ks, ksmax, delta, tol, dim, init_pos, orig_pos, plotstep)
}

